### ISSUE TITLE
favicon 수정

### ISSUE THREAD

**Issue by MinHyeoks** [jjangga0214/mama-index#14]
제곧내

**Comment by jjangga0214** [comment]
### 현재 후보
* MAMA의 로고를 응용하여, M과 A를 동시에 표현하려고 했음.  
* 대각으로 배치하여 도발적인 분위기를 내보려고 시도.
* 64x64  

![mama-favicon](https://user-images.githubusercontent.com/28584151/41880818-194d8978-791b-11e8-8bb7-7ad6b41d8441.png)

**Comment by MinHyeoks** [comment]
아멘..


2018-06-26 8:32 GMT+09:00 jjangga0214 <notifications@github.com>:
